task: 'if_nerf'
gpus: [0]

parent_cfg: 'configs/zju_mocap_exp/latent_xyzc_313.yaml'

human: 396

train_dataset:
    data_root: 'data/zju_mocap/CoreView_396'
    human: 'CoreView_396'
    ann_file: 'data/zju_mocap/CoreView_396/annots.npy'
    split: 'train'

test_dataset:
    data_root: 'data/zju_mocap/CoreView_396'
    human: 'CoreView_396'
    ann_file: 'data/zju_mocap/CoreView_396/annots.npy'
    split: 'test'

# data options
num_train_frame: 540
begin_ith_frame: 810
