task: 'if_nerf'
gpus: [0]

parent_cfg: 'configs/nerf/nerf_313.yaml'

human: 393

train_dataset:
    data_root: 'data/zju_mocap/CoreView_393'
    human: 'CoreView_393'
    ann_file: 'data/zju_mocap/CoreView_393/annots.npy'
    split: 'train'

test_dataset:
    data_root: 'data/zju_mocap/CoreView_393'
    human: 'CoreView_393'
    ann_file: 'data/zju_mocap/CoreView_393/annots.npy'
    split: 'test'
