task: 'if_nerf'
gpus: [0]

parent_cfg: 'configs/zju_mocap_exp/latent_xyzc_313.yaml'

human: 313

train_dataset:
    data_root: 'data/zju_mocap/CoreView_313'
    human: 'CoreView_313'
    ann_file: 'data/zju_mocap/CoreView_313/annots.npy'
    split: 'train'

test_dataset:
    data_root: 'data/zju_mocap/CoreView_313'
    human: 'CoreView_313'
    ann_file: 'data/zju_mocap/CoreView_313/annots.npy'
    split: 'test'

# data options
smpl: 'smpl_6view'
params: 'params_6view'
vertices: 'vertices_6view'
training_view: [0, 3, 6, 12, 15, 18]
